### ISSUE TITLE
Update new feature to learn issue in github

### ISSUE THREAD

**Issue by KeerthanaAngappan97** [KeerthanaAngappan/FirstDev#3]
Dear Keerthana,

I review your code, please add how to learn about issue in github. 
Kindly add this feature in your code.

**Comment by KeerthanaAngappan** [comment]
Dear Keerthana97,

Thanks for your suggestion, we will work on it.

**Comment by KeerthanaAngappan** [comment]
Dear Keerthana97,

This feature is added to your project.
